### ISSUE TITLE
Changing the default compiler

### ISSUE THREAD

**Issue by jakobkogler** [gabrielsimoes/cfparser.vim#10]
I already mentioned this in #9. But since the pull-request is already close, I'm afraid it will not get seen.

We should provide an option to change the compiler in the .vimrc. Currently you manually have to change the plugin if you want to use a different compiler. E.g. writing `let g:cf_pl_by_ext['.cpp'] = g:cf_pl_gpp14` or `let g:cf_pl_ext['.cpp'] = 42` in the `.vimrc` doesn't work, since the the plugin loads after the `.vimrc` and overwrites the dict.

**Comment by gabrielsimoes** [comment]
Good idea. I added a way to change configuration at commits 39b76da75d63588ced5044834640dddc214d812a and bcaf5b509ccf16e6d9f4c098c69763b9e47427e6.

**Comment by Debabrata557** [comment]
When I am trying to Login It shows me below message.
`Error detected while processing function cfparser#CFLogin[11]..cfparser#CFGetToken:
line    3:
E684: list index out of range: 1
E15: Invalid expression: match[1]
`

Actually I am behind a proxy.Does this work with proxy?
