### ISSUE TITLE
Issue in login

### ISSUE THREAD

**Issue by Debabrata557** [gabrielsimoes/cfparser.vim#11]
When I am trying to Login It shows me below message.
`Error detected while processing function cfparser#CFLogin[11]..cfparser#CFGetToken:
line    3:
E684: list index out of range: 1
E15: Invalid expression: match[1]
`

Actually I am behind a proxy.Does this work with proxy?

**Comment by gabrielsimoes** [comment]
I'll take a look into that later. It should work, as long as curl is using the proxy settings. Are you on Linux? Could you try creating a `~/.curlrc` file with something like the following:

```
proxy = server.something.com:1234
proxy-user = "foo:bar"
```

More information here: https://www.cyberciti.biz/faq/linux-unix-curl-command-with-proxy-username-password-http-options/amp/

**Comment by gabrielsimoes** [comment]
I'll close this for inactivity. Tell me if you couldn't solve the problem, or if you solved it differently.
