### ISSUE TITLE
Enhancement: store username and password

### ISSUE THREAD

**Issue by jakobkogler** [gabrielsimoes/cfparser.vim#13]
Inputting name and password for each submission is pretty lame.

I usually make a local branch of this repo, and replace the lines:

    let s:cf_uname = input('username: ')
    let s:cf_passwd = inputsecret('password: ')
    let remember = input('remember? [Y/n] ')
    if remember ==? "n"
        let s:cf_remember = 1
    else
        let s:cf_remember = 0
    endif

with 

    let s:cf_uname = "myhandle"
    let s:cf_passwd = "mysecretpassword"
    let s:cf_remember = 1

But this is not really a good way.
And especially not really useful for people who are afraid to read vimscript.

Maybe somebody has an idea for an better, easier to setup, and also more secure way.
E.g. setting the password in the vimrc is not a good approach.
Maybe storing the password in a local file and encrypt it with gpg.

**Comment by gnull** [comment]
Isn't this feature already implemented through saving cookies when `cfparser.vim` logs in with `curl`?

You log in once, `curl` saves your session into `~/.cf_cookies`, and you freely perform your requests to Codeforces for a month without any more logins. I thought this is how it is supposed to work. Why do you need to hardcode your password in source code?

PS. This post might be a bit irrelevant, through I don't use `cfparser.vim` frequently.

**Comment by gnull** [comment]
> E.g. setting the password in the vimrc is not a good approach.
> Maybe storing the password in a local file and encrypt it with gpg.

This doesn't seem to be very reasonable, because when you log in to codeforces via `http` your password is transmitted over the network in paintext anyway. Anyone with access to your network can intercept your password trivially using a network sniffer like `ettercap`.

**Comment by jakobkogler** [comment]
@gnull Oh, wow.
How could I forgot about this.

I think at one point (a few months ago) this didn't work, and since then I hardcoded the password into the source code, thinking that it was necessary.
Not sure why it didn't work back then.

Anyways, I just tried it with, and the `~/.cf_cookie` thing works like a charm.

**Comment by gabrielsimoes** [comment]
I'm surprised CodeForces doesn't use `https`. (Hadn't noticed before)
