### ISSUE TITLE
parses '>' as '>' instead of 'gt'

### ISSUE THREAD

**Issue by DylanGuedes** [gabrielsimoes/cfparser.vim#17]
Hi

for problems with a '>', '<' or similars in the input (like [this one](https://codeforces.com/contest/1131/problem/D)), it downloads the input as 'gt', instead of '>'.

**Comment by jakobkogler** [comment]
The problem is, that there are actually `&gt;` and similar HTML entities in the page source, and just the browser renders them as their actual characters.

I made a pull-request that converts those HTML entities sequences into their correct symbols.
