### ISSUE TITLE
why shows this error?

### ISSUE THREAD

**Issue by jewel-nath** [gabrielsimoes/cfparser.vim#21]
g++: error: /home/devjewel/Documents/C++/1470A.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.

TEST 1
zsh:2: no such file or directory: /tmp/cfparser_exec
                                                              > 30
                                                              > 190

TEST 2
zsh:2: no such file or directory: /tmp/cfparser_exec
                                                              > 1
rm: cannot remove '/tmp/cfparser_exec': No such file or directory

**Comment by jakobkogler** [comment]
Are you sure that you have your solution file located at `/home/devjewel/Documents/C++/1470A.cpp`?
Have you actually saved the file?
