### ISSUE TITLE
CFLastsubmissions

### ISSUE THREAD

**Issue by asperaa** [gabrielsimoes/cfparser.vim#3]
I'm getting the following error on using `:CFLastSubmissions<CR>` command:-
`Error detected while processing function cfparser#CFLastSubmissions:                                           
line    8:
E706: Variable type mismatch for: cf_response
line   10:
E121: Undefined variable: status
E116: Invalid arguments for function matchstr(cf_response.status, "OK"))
E116: Invalid arguments for function empty(matchstr(cf_response.status, "OK"))
E15: Invalid expression: empty(matchstr(cf_response.status, "OK"))`

**Comment by gabrielsimoes** [comment]
Just tested and it worked fine for me, are you logged in?

**Comment by gabrielsimoes** [comment]
Actually, looking at it more carefully, seems the codeforces API response was invalid. Maybe codeforces API was offline at the time or there was some failure in the network. Could you check if it is working now?

**Comment by asperaa** [comment]
Yes,I'm logged in.
No,it's still not working.All the other commands are working fine except `:CFLastSubmissions<CR>` and `CFRun<CR>`

**Comment by gabrielsimoes** [comment]
What is the output with `CFRun`? Are you on linux or windows? Do you have `curl`installed? What's your vim version?

**Comment by asperaa** [comment]
I'm on linux. Yes, Curl is installed.
CFRun shows an error.

**Comment by gabrielsimoes** [comment]
Which error does CFRun show? Also, whats your VIM version?

**Comment by asperaa** [comment]
CFRun shows the following error:
  "Error detected while processing function cfparser#CFRun:
line    2:
E492: Not an editor command:     RunInInteractiveShell /tmp/cfparser_exec
Press ENTER or type command to continue
"
vim version is 7.4.52

**Comment by gabrielsimoes** [comment]
Just noticed `CFRun` depends on another VIM plugin I use. Now it should work fine. However, I have no clue what my be causing the error on `CFLastSubmissions`. Are you behind a proxy or something?

**Comment by asperaa** [comment]
CFRun is working fine now.
I'm not behind any proxy.

**Comment by gabrielsimoes** [comment]
Could you run this and post the output here: `curl --location --silent 'http://codeforces.com/api/user.status?handle=aspera_&from=1&count=5'`
Also run this on vim `:echo cfparser#CFLoggedInAs()` and post the output here.

**Comment by gabrielsimoes** [comment]
I have made some changes, could you check if it is working now?

**Comment by gabrielsimoes** [comment]
If it still errors, please post the new output.

**Comment by asperaa** [comment]
It's working fine.Thanks for all the help :).
